### ISSUE TITLE
Incorrect get_users function result

### ISSUE THREAD

**Issue by PaulVinar** [Gennadynemchin/Yandex.Tracker_changelogins#2]
Привет!

В модуле [mapping_users.py](https://github.com/Gennadynemchin/Yandex.Tracker_changelogins/blob/master/mapping_users.py), в цикле функции get_users итериативно происходит переопределение переменной elements. Это приводит к тому, что если фактическое число пользователей, например 1к, а perPage = 100, то сама функция вернёт 100 человек последней, 10-й страницы.

**Comment by Gennadynemchin** [comment]
Исправил ошибку: [добавил](https://github.com/Gennadynemchin/Yandex.Tracker_changelogins/commit/59919151e40659e5221923a41efd36c723195e83) в функцию get_users() список с добавлением через extend(). Пока только в ветке dev.
